### ISSUE TITLE
Release 2.5 - CTS test case failure (inmem)

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#4168]
Running the CTS against 2.5 results in the following failure with the in-memory repository

```
               "failedTestCases": [
                    {
                        "class": "OpenMetadataTestCaseResult",
                        "notSupportAssertions": [],
                        "successfulAssertions": [
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
                            "repository-entity-retype-17: OpenMetadataRoot repository supports creation of instances.",
                            "repository-entity-retype-01: OpenMetadataRoot new entity created.",
                            "repository-entity-retype-02: OpenMetadataRoot new entity retrieved.",
                            "repository-entity-retype-18: OpenMetadataRoot repository supports retype of instances of type ",
                            "repository-entity-retype-03: OpenMetadataRoot entity is retyped.",
                            "repository-entity-retype-04: OpenMetadataRoot retyped entity has expected type.",
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite."
                        ],
                        "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-entity-retype-test-case.md",
                        "testCaseId": "repository-entity-retype-OpenMetadataRoot",
                        "testCaseName": "Repository entity retype test case",
                        "unsuccessfulAssertions": [
                            "repository-entity-retype-05: OpenMetadataRoot retyped entity has expected properties."
                        ]
                    }
```

The test environment was the CTS notebook running in k8s

Test repeated twice.

Could this have been introduced by #4117 / #4105
I suspect the cts needs updating to match? @grahamwallis @mandy-chessell

**Comment by grahamwallis** [comment]
At a quick glance (I have not run the test) it looks to me like we need an extra null test in the following:

    private boolean doPropertiesMatch(InstanceProperties firstInstanceProps, InstanceProperties secondInstanceProps)
    {
        boolean matchProperties = false;
        boolean noProperties = false;

        if ( (secondInstanceProps == null) ||
             (secondInstanceProps.getInstanceProperties() == null) ||
             (secondInstanceProps.getInstanceProperties().isEmpty()))
        {
            noProperties = true;
        }

        if (noProperties)
        {         <<<<==== should check for firstInstanceProps == null !!
            if ((firstInstanceProps.getInstanceProperties() == null) ||
                (firstInstanceProps.getInstanceProperties().isEmpty()))
            {
                matchProperties = true;
            }
        }
        else
        {
            // non-empty, perform matching
           ...etc...


I have a feeling this might be the first entity type that actually has no properties.


A similar problem might exist in other entity instance test cases that have the doPropertiesMatch method, such as the reidentify test case.

**Comment by planetf1** [comment]
Do you feel we should fix CTS before release? Though the bug seems minor, if we are asserting CTS is a gold tick on the connectors we should really get it working.

So would be ideal, but That being said, if it's non trivial I would recommend we add to the release notes instead

**Comment by grahamwallis** [comment]
@planetf1 - yes, good point. We should fix this before release of 2.5.

**Comment by grahamwallis** [comment]
@planetf1 - I will do it this morning

**Comment by planetf1** [comment]
After the CTS Fix with in-memory, I am still seeing some failures:
```
Date of conformance test:          2020-12-08T09:38:41.901+00:00
Number of tests that were run:     4636
Number of tests that failed:       3
Number of tests that were skipped: 0
```
```
                "failedTestCases": [
                    {
                        "class": "OpenMetadataTestCaseResult",
                        "conformanceException": {
                            "errorMessage": "CTS test repository-entity-proxy-lifecycle caught exception AssertionFailureException from method getEntityDetail whilst trying to retrieve an entity of type GlossaryTerm.  Exception message was : Failed Assertion:  repository disallows retrieval of entity proxy as an EntityDetail for type GlossaryTerm.  Method was invoked with parameters: entityGUID : 7065e377-13e0-4355-9bcb-2bd48d6f166a",
                            "exceptionClassName": "java.lang.Exception"
                        },
                        "notSupportAssertions": [],
                        "successfulAssertions": [
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
                            "repository-entity-proxy-lifecycle-2:  repository does not support creation of entity proxies for type GlossaryTerm",
                            "repository-entity-proxy-lifecycle-2:  repository does not support creation of entity proxies for type GlossaryTerm",
                            "repository-entity-proxy-lifecycle-03:  repository supports retrieval of entity proxy as an EntitySummary for type GlossaryTerm",
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite."
                        ],
                        "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-entity-proxy-lifecycle-test-case.md",
                        "testCaseId": "repository-entity-proxy-lifecycle-ISARelationship",
                        "testCaseName": "Repository entity proxy lifecycle test case",
                        "unsuccessfulAssertions": [
                            "repository-entity-proxy-lifecycle-04:  repository disallows retrieval of entity proxy as an EntityDetail for type GlossaryTerm",
                            "Unexpected Exception Exception : CTS test repository-entity-proxy-lifecycle caught exception AssertionFailureException from method getEntityDetail whilst trying to retrieve an entity of type GlossaryTerm.  Exception message was : Failed Assertion:  repository disallows retrieval of entity proxy as an EntityDetail for type GlossaryTerm.  Method was invoked with parameters: entityGUID : 7065e377-13e0-4355-9bcb-2bd48d6f166a"
                        ]
                    },
                    {
                        "class": "OpenMetadataTestCaseResult",
                        "conformanceException": {
                            "errorMessage": "CTS test repository-entity-proxy-lifecycle caught exception AssertionFailureException from method getEntitySummary whilst trying to retrieve an entity of type Referenceable.  Exception message was : Failed Assertion:  repository supports delete of entity proxy of type Referenceable.  Method was invoked with parameters: entityGUID : a62b49c9-025b-488d-a693-ed12d3a6ab30",
                            "exceptionClassName": "java.lang.Exception"
                        },
                        "notSupportAssertions": [],
                        "successfulAssertions": [
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
                            "repository-entity-proxy-lifecycle-2:  repository does not support creation of entity proxies for type Referenceable",
                            "repository-entity-proxy-lifecycle-2:  repository does not support creation of entity proxies for type GlossaryTerm",
                            "repository-entity-proxy-lifecycle-03:  repository supports retrieval of entity proxy as an EntitySummary for type Referenceable",
                            "repository-entity-proxy-lifecycle-04:  repository disallows retrieval of entity proxy as an EntityDetail for type Referenceable",
                            "repository-entity-proxy-lifecycle-05:  repository disallows isEntityKnown for entity proxy for type Referenceable",
                            "repository-entity-proxy-lifecycle-09: SupplementaryProperties entity proxy status cannot be updated ",
                            "repository-entity-proxy-lifecycle-09: SupplementaryProperties entity proxy status cannot be updated ",
                            "repository-entity-proxy-lifecycle-10: SupplementaryProperties entity proxy properties cannot be updated ",
                            "repository-entity-proxy-lifecycle-11: SupplementaryProperties entity proxy type cannot be updated ",
                            "repository-entity-proxy-lifecycle-12: SupplementaryProperties entity proxy identity cannot be updated ",
                            "repository-entity-proxy-lifecycle-06:  repository does not support creation of relationship instance for type SupplementaryProperties",
                            "repository-entity-proxy-lifecycle-07:  repository supports soft delete of relationship instance for type SupplementaryProperties",
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite."
                        ],
                        "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/test-cases/repository-entity-proxy-lifecycle-test-case.md",
                        "testCaseId": "repository-entity-proxy-lifecycle-SupplementaryProperties",
                        "testCaseName": "Repository entity proxy lifecycle test case",
                       "unsuccessfulAssertions": [
                            "repository-entity-proxy-lifecycle-08:  repository supports delete of entity proxy of type Referenceable",
                            "Unexpected Exception Exception : CTS test repository-entity-proxy-lifecycle caught exception AssertionFailu
reException from method getEntitySummary whilst trying to retrieve an entity of type Referenceable.  Exception message was : Failed Asse
rtion:  repository supports delete of entity proxy of type Referenceable.  Method was invoked with parameters: entityGUID : a62b49c9-025
b-488d-a693-ed12d3a6ab30"
                        ]
                    },
                    {
                        "class": "OpenMetadataTestCaseResult",
                        "conformanceException": {
                            "errorMessage": "CTS test repository-entity-proxy-lifecycle caught exception AssertionFailureException from
method getEntityDetail whilst trying to retrieve an entity of type RelationalColumn.  Exception message was : Failed Assertion:  reposit
ory disallows retrieval of entity proxy as an EntityDetail for type RelationalColumn.  Method was invoked with parameters: entityGUID :
b0abf114-65e6-4d17-9105-1ed94578c539",
                            "exceptionClassName": "java.lang.Exception"
                        },
                        "notSupportAssertions": [],
                        "successfulAssertions": [
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite.",
                            "repository-entity-proxy-lifecycle-2:  repository does not support creation of entity proxies for type Relat
ionalColumn",
                            "repository-entity-proxy-lifecycle-2:  repository does not support creation of entity proxies for type Relat
ionalColumn",
                            "repository-entity-proxy-lifecycle-03:  repository supports retrieval of entity proxy as an EntitySummary fo
r type RelationalColumn",
                            "repository-test-case-base-01: Repository connector supplied to conformance suite.",
                            "repository-test-case-base-02: Metadata collection for repository connector supplied to conformance suite."
                        ],
                        "testCaseDescriptionURL": "https://egeria.odpi.org/open-metadata-conformance-suite/docs/repository-workbench/tes
t-cases/repository-entity-proxy-lifecycle-test-case.md",
                        "testCaseId": "repository-entity-proxy-lifecycle-ForeignKey",
                        "testCaseName": "Repository entity proxy lifecycle test case",
                        "unsuccessfulAssertions": [
                            "repository-entity-proxy-lifecycle-04:  repository disallows retrieval of entity proxy as an EntityDetail fo
r type RelationalColumn",
                            "Unexpected Exception Exception : CTS test repository-entity-proxy-lifecycle caught exception AssertionFailu
reException from method getEntityDetail whilst trying to retrieve an entity of type RelationalColumn.  Exception message was : Failed As
sertion:  repository disallows retrieval of entity proxy as an EntityDetail for type RelationalColumn.  Method was invoked with paramete
rs: entityGUID : b0abf114-65e6-4d17-9105-1ed94578c539"
                        ]
                    }
                ],
```

**Comment by planetf1** [comment]
a) The original problem should be fixed now and is merged into 2.5 - will reopen if any errors resurface
b) In the second run the cohort was 'dirty' with another notebook having created additional servers etc in the cluster
