### ISSUE TITLE
FVTs clash in use of port numbers

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria#6011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In https://github.com/odpi/egeria/pull/5957 stewardship-action moved to port 10453 from 10455 (in maven & gradle)

The current usage is
 - data engine - 9999 (from it's application.properties)
 
 and
 ```
 ./access-services-fvt/asset-owner-fvt/pom.xml:        <fvt.serverport>10445</fvt.serverport>
./access-services-fvt/governance-program-fvt/pom.xml:        <fvt.serverport>10452</fvt.serverport>
./access-services-fvt/discovery-engine-fvt/pom.xml:        <fvt.serverport>10450</fvt.serverport>
./access-services-fvt/stewardship-action-fvt/pom.xml:        <fvt.serverport>10453</fvt.serverport>
./access-services-fvt/data-manager-fvt/pom.xml:        <fvt.serverport>10446</fvt.serverport>
./access-services-fvt/asset-manager-fvt/pom.xml:        <fvt.serverport>10444</fvt.serverport>
./access-services-fvt/community-profile-fvt/pom.xml:        <fvt.serverport>10449</fvt.serverport>
./access-services-fvt/asset-consumer-fvt/pom.xml:        <fvt.serverport>10443</fvt.serverport>
./access-services-fvt/subject-area-fvt/pom.xml:        <fvt.serverport>10448</fvt.serverport>
./access-services-fvt/governance-engine-fvt/pom.xml:        <fvt.serverport>10451</fvt.serverport>
./access-services-fvt/digital-architecture-fvt/pom.xml:        <fvt.serverport>10447</fvt.serverport>
./access-services-fvt/analytics-modeling-fvt/pom.xml:		<fvt.serverport>10453</fvt.serverport>
```

### Expected Behavior

No use of same ports

### Steps To Reproduce

n/a

### Environment

```markdown
- Egeria:
- OS:
- Java:
- Browser (for UI issues):
- Additional connectors and integration:
```

### Any Further Information?

10453 is already used by analytics modelling, 10455 is not, so this port can be put back to 10455

This is needed so that when running parallel builds in gradle or maven we do not get a clash if tests run in parallel

Ideally we would have some co-ordination of ports used, or defaults -- but this requires more work in the pom/build.gradle For now the 'inspection' approach is what we have.

**Comment by planetf1** [comment]
After fix
```
 jonesn:open-metadata-fvt/ (issue6011*) $ find . -type f -name build.gradle -print | xargs -n50 grep -y 10453                                                                                 [18:18:31]
./access-services-fvt/analytics-modeling-fvt/build.gradle:    args = [ "-Dserver.port=10453",
./access-services-fvt/analytics-modeling-fvt/build.gradle:    waitForPort = 10453
./access-services-fvt/analytics-modeling-fvt/build.gradle:            'baseURL': 'https://localhost:10453',
./access-services-fvt/analytics-modeling-fvt/build.gradle:            'fvt.url': 'https://localhost:10453'
jonesn:open-metadata-fvt/ (issue6011*) $ find . -type f -name build.gradle -print | xargs -n50 grep -y 10455                                                                                 [18:18:47]
./access-services-fvt/stewardship-action-fvt/build.gradle:    args = [ "-Dserver.port=10455",
./access-services-fvt/stewardship-action-fvt/build.gradle:    waitForPort = 10455
./access-services-fvt/stewardship-action-fvt/build.gradle:            'baseURL': 'https://localhost:10455',
./access-services-fvt/stewardship-action-fvt/build.gradle:            'fvt.url': 'https://localhost:10455'
jonesn:open-metadata-fvt/ (issue6011*) $ find . -type f -name pom.xml -print | xargs -n50 grep -y 10453                                                                                      [18:18:51]
./access-services-fvt/analytics-modeling-fvt/pom.xml:		<fvt.serverport>10453</fvt.serverport>
jonesn:open-metadata-fvt/ (issue6011*) $ find . -type f -name pom.xml -print | xargs -n50 grep -y 10455                                                                                      [18:19:00]
./access-services-fvt/stewardship-action-fvt/pom.xml:        <fvt.serverport>10455</fvt.serverport>
```

**Comment by mandy-chessell** [comment]
This has been fixed twice - I added a PR for this also ...

**Comment by planetf1** [comment]
@mandy-chessell This issue remains. From current master

```
find . -type f -name build.gradle -print | xargs -n50 grep -y 10453          [9:33:55]
./open-metadata-test/open-metadata-fvt/access-services-fvt/stewardship-action-fvt/build.gradle:    args = [ "-Dserver.port=10453",
./open-metadata-test/open-metadata-fvt/access-services-fvt/stewardship-action-fvt/build.gradle:    waitForPort = 10453
./open-metadata-test/open-metadata-fvt/access-services-fvt/stewardship-action-fvt/build.gradle:            'baseURL': 'https://localhost:10453',
./open-metadata-test/open-metadata-fvt/access-services-fvt/stewardship-action-fvt/build.gradle:            'fvt.url': 'https://localhost:10453'
./open-metadata-test/open-metadata-fvt/access-services-fvt/analytics-modeling-fvt/build.gradle:    args = [ "-Dserver.port=10453",
./open-metadata-test/open-metadata-fvt/access-services-fvt/analytics-modeling-fvt/build.gradle:    waitForPort = 10453
./open-metadata-test/open-metadata-fvt/access-services-fvt/analytics-modeling-fvt/build.gradle:            'baseURL': 'https://localhost:10453',
./open-metadata-test/open-metadata-fvt/access-services-fvt/analytics-modeling-fvt/build.gradle:            'fvt.url': 'https://localhost:10453'
```
as per the original issue.

There is a PR open, which I believe is good to merge. See https://github.com/odpi/egeria/pull/6012

Was it this PR you were referring to (, or have a misinterpreted the current code?

I don't see any outstanding PR with the fix ?
